<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>disable</Nullable>
        <AssemblyName>LQTestStagingVanilla</AssemblyName>
        <RootNamespace>LQTestStagingVanilla</RootNamespace>
        <OutputPath>..\Assemblies\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <DebugType>none</DebugType>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*" />
        <PackageReference Include="Lib.Harmony" Version="2.3.3" ExcludeAssets="runtime" />
    </ItemGroup>

    <ItemGroup>
        <Reference Include="PawnsOptimizeWeaponQuality">
            <HintPath>../../../Assemblies/PawnsOptimizeWeaponQuality.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

</Project>
